apiVersion: v1
kind: PersistentVolume
metadata:
  name: patrick-pv-vol
  labels:
    type: local1
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/pv-data"  # For aws "home/ubuntu/pv-data"
