apiVersion: v1
kind: PersistentVolume
metadata:
  name: patrick-pv-vol-1
  labels:
    type: local2
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/pv-dat2"  # For aws "home/ubuntu/pv-data"
