apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patrick-pv-claim
spec:
  selector:
    matchLabels:
      type: "local2"
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
